[build]
  base = "test-react-app"
  command = "CI=false npm run build"
  publish = "test-react-app/build"

[build.environment]
  NODE_VERSION = "20.18.0"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200